definitions:
  logistics.Commande:
    properties:
      Magsin:
        type: string
      ProduitID:
        type: integer
      host:
        type: string
      id:
        type: integer
      message:
        type: string
    type: object
  models.ApiError:
    properties:
      error:
        type: string
      message:
        type: string
      path:
        type: string
      status:
        type: integer
      success:
        type: boolean
      timestamp:
        type: string
    type: object
  models.ApiSuccess:
    properties:
      message:
        type: string
      path:
        type: string
      status:
        type: integer
      success:
        type: boolean
      timestamp:
        type: string
    type: object
  models.Produit:
    properties:
      category:
        type: string
      description:
        type: string
      id:
        type: integer
      nom:
        type: string
      prix:
        type: number
      quantite:
        type: integer
    type: object
host: localhost/logistique
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is the API for the Centre Logistique service.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Centre Logistique API
  version: "1.0"
paths:
  /api/v1/commande/{id}:
    delete:
      description: Refuse a command
      parameters:
      - description: Command ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ApiSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ApiError'
      security:
      - BearerAuth: []
      summary: Refuse Command
      tags:
      - commands
    put:
      description: Accept a command
      parameters:
      - description: Command ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ApiSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ApiError'
      security:
      - BearerAuth: []
      summary: Accept Command
      tags:
      - commands
  /api/v1/commande/{magasin}/{id}:
    post:
      consumes:
      - application/json
      description: Create a new command
      parameters:
      - description: Magasin
        in: path
        name: magasin
        required: true
        type: string
      - description: Command ID
        in: path
        name: id
        required: true
        type: integer
      - description: Host
        in: body
        name: body
        required: true
        schema:
          properties:
            host:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ApiSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ApiError'
      security:
      - BearerAuth: []
      summary: Create Command
      tags:
      - commands
  /api/v1/commands:
    get:
      description: Get all commands
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/logistics.Commande'
            type: array
      security:
      - BearerAuth: []
      summary: Get All Commands
      tags:
      - commands
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: Authenticates an employee with the Mere system
      parameters:
      - description: Login Credentials
        in: body
        name: body
        required: true
        schema:
          properties:
            password:
              type: string
            username:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              token:
                type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ApiError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: Login
      tags:
      - auth
  /api/v1/produit/{id}:
    put:
      consumes:
      - application/json
      description: Updates a product
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: Product Update Data
        in: body
        name: product
        required: true
        schema:
          properties:
            description:
              type: string
            nom:
              type: string
            prix:
              format: float64
              type: number
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ApiSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: Update Product
      tags:
      - produits
  /api/v1/produits/{nom}:
    get:
      description: Find a product by name
      parameters:
      - description: Product Name
        in: path
        name: nom
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Produit'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ApiError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: Find Product
      tags:
      - produits
  /api/v1/produits/id/{id}:
    get:
      description: Find a product by id
      parameters:
      - description: Product Name
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Produit'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ApiError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: Find Product
      tags:
      - produits
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
